# mkdocs.yml
site_name: "pbi_cli Documentation"
site_author: ""
site_description: "Documentation for pbi_cli - a command line interface for Power BI."
site_url: "https://emptymalei.github.io/powerbi-cli"
repo_url: "https://github.com/emptymalei/powerbi-cli"
edit_uri: "blob/main/docs/"
repo_name: "emptymalei/powerbi-cli"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/logo.png
  # logo: assets/logo_transparent.png



markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "¤"
  - mkdocs-click

plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            filters:
  - mkdocs-jupyter:
      execute: True
      allow_errors: false
      include_requirejs: true

watch:
  - docs
  - src/pbi_cli

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "Home": index.md
  - References:
    - "Introduction": references/index.md
    - "pbi_cli":
      - "cli": references/cli.md
      - "powerbi":
        - "index": references/powerbi/index.md
        - "admin": references/powerbi/admin.md
        - "app": references/powerbi/app.md
        - "base": references/powerbi/base.md
        - "io": references/powerbi/io.md
        - "report": references/powerbi/report.md
  - "Changelog": changelog.md
