"""Generate ``docs/references/cli.md`` from the ``pbi`` command definitions.

The CLI reference is built from the help text of the commands themselves, so it cannot
drift from the CLI. Run it after changing a command, option or docstring::

    uv run python scripts/gen_cli_docs.py           # rewrite the page
    uv run python scripts/gen_cli_docs.py --check   # exit 1 if the page is out of date

``tests/test_cli_docs.py`` runs the check, so a stale page fails the test suite.
"""

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "docs" / "references" / "cli.md"

HEADER = (
    "<!-- This page is generated by scripts/gen_cli_docs.py from the command"
    " definitions. Do not edit it by hand: change the docstrings and options in"
    " src/pbi_cli/cli.py and run `uv run python scripts/gen_cli_docs.py`. -->\n\n"
)

FOOTER = """
## Auxiliary Functions

::: pbi_cli.cli
"""


def render_page() -> str:
    """Return the Markdown of the CLI reference page."""
    with tempfile.TemporaryDirectory() as tmp:
        generated = Path(tmp) / "cli.md"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "typer",
                "pbi_cli.cli",
                "utils",
                "docs",
                "--name",
                "pbi",
                "--title",
                "CLI",
                "--output",
                str(generated),
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        body = generated.read_text(encoding="utf-8")
    return HEADER + body.rstrip() + "\n" + FOOTER


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the page is out of date",
    )
    args = parser.parse_args()

    page = render_page()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != page:
            print(
                f"{OUTPUT.relative_to(REPO_ROOT)} is out of date. "
                "Run: uv run python scripts/gen_cli_docs.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(page, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
